#ifndef ERROR_H
#define ERROR_H

typedef enum {
  LATO_OK = 0,
  LATO_ERR_OUT_OF_MEMORY,
  LATO_ERR_FT_INIT,
  LATO_ERR_FT_FACE,
  LATO_ERR_FT_PIXEL_SIZE,
  LATO_ERR_FT_LOAD_CHAR,
  LATO_ERR_FT_RENDER_GLYPH,
  LATO_ERR_FC_INIT,
  LATO_ERR_FC_LOAD_CONFIG,
  LATO_ERR_FC_NAME_PARSE,
  LATO_ERR_FC_FONT_MATCH,
} LatoErrorCode;

#endif
